version: '2.17.3'
services: 
  opencv:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 5000:5000
    volumes:
      - ./server.py:/server.py
      - ./mainModule.py:/mainModule.py
      - ./Modules:/Modules
      - ./utils:/utils
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONDONTWRITEBYTECODE=TRUE